version: 2

variables:
  linux: &linux
    docker:
      - image: cmriprocan/cci-ruviii_c-docker-primary:3.6.1

  linux_setup: &linux_setup
    run:
      name: Setting up build environment
      command: |
        apt update
        apt install -y gnupg curl

        VER=18.09.3
        curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
        tar -xz -C /tmp -f /tmp/docker-$VER.tgz
        mv /tmp/docker/* /usr/bin       

  package_build: &package_build
    run:
      name: Building package
      command: |
        R CMD INSTALL .

  test: &test
    run:
      name: Testing package
      command: |
        cd tests && R -e "source('./testthat.R')"

  version_info: &version_info
    run:
      name: Calculating new version, docker, and git tags
      command: |
        version=$(cat version)

        if [ "${CIRCLE_BRANCH}" != "master" ]; then
          version=$(cat version | perl -pe 's/^((\d+\.)*)(\d+)(.*)$/$1.($3+1).$4/e')
          version="${version//\//}"  # also remove slashes!
          printf ${version} > version
        else
          # add the branch name, but remove any dashes to make it fit with PEP-440
          version="${version}.${CIRCLE_BRANCH//-/}"
          # limit length to Docker's limit of 128 chars
          version=${version:0:125}
        fi

        printf 'export VERSION=%s\n' "${version}" >> $BASH_ENV
        printf 'export NEW_GIT_TAG=%s\n' "${version}" >> $BASH_ENV
        printf 'export IMAGE=%s/%s\n' "${CIRCLE_PROJECT_USERNAME}" "${CIRCLE_PROJECT_REPONAME}" >> $BASH_ENV
        printf 'export DOCKER_FLAG=${IMAGE}:${NEW_GIT_TAG}\n' >> $BASH_ENV

        source $BASH_ENV

  docker_build: &docker_build
    run:
      name: Building docker image
      command: |
        source $BASH_ENV

        sh +x -c 'echo $DOCKER_PASSWORD' | docker login -u ${DOCKER_USER} --password-stdin

        echo $BITBUCKET_PASSWORD > bitbucket_pw.txt

        DOCKER_BUILDKIT=1 docker build \
          --network host \
          --secret \
          --build-arg bitbucket_user="${BITBUCKET_USER}" \
          id=gitpassword,src=$(pwd)/gitpassword.txt \
          -t ${DOCKER_FLAG} docker/Dockerfile
  
  publish: &publish
    run:
      name: Publishing new docker image and git version
      command: |
        source $BASH_ENV

        if [ "${CIRCLE_BRANCH}" == "master" ]; then
          git remote set-url origin https://${BITBUCKET_USER}:${BITBUCKET_PASSWORD}@bitbucket.org/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git
          git config --global user.email "procansoftengrobot@cmri.com.au"
          git config --global user.name "ProCan Soft Eng Robot"
          git diff --quiet version || git commit version -m "[skip ci] ${IMAGE} updated to ${VERSION}"

          git tag ${NEW_GIT_TAG}

          git push origin ${NEW_GIT_TAG}
          git push origin ${CIRCLE_BRANCH}

          docker push ${DOCKER_FLAG}
        fi

jobs:
  build-linux:
    <<: *linux
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - *linux_setup
      - *package_build
      - *test
      - *version_info
      - *docker_build
      - *publish

workflows:
  version: 2
  ruviii-c-test:
    jobs:
      - build-linux
