version: 2

variables:
  linux: &linux
    docker:
      - image: cmriprocan/cci-ruviii_c-docker-primary:3.6.1

  build: &build
    run:
      command: |
        R CMD INSTALL .

  common: &common
    run:
      command: |
        printf 'export WORKSPACE=%s\n' $(pwd) >> $BASH_ENV
  test: &test
    run:
      command: |
        cd ${WORKSPACE}/tests && R -e "source('./testthat.R')"

jobs:
  build-linux:
    <<: *linux
    steps:
      - *common
      - checkout
      - *build
      - *test

workflows:
  version: 2
  ruviii-c-test:
    jobs:
      - build-linux
