# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RUVIIIC_CPP <- function(input, k, M, controls, toCorrect, withW) {
        if(any(is.na(input[, controls])))
        {
                stop("The negative control variables should never be NA")
        }
	if(k >= nrow(input))
	{
		stop("Input k cannot be larger than the number of rows in the input matrix")
	}
	if(k >= length(controls))
	{
		stop("Input k cannot be larger than the number of negative controls")
	}
    	.Call('_RUVIIIC_RUVIIIC', PACKAGE = 'RUVIIIC', input, k, M, controls, toCorrect, withW)
}

