# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RUVIII_C_CPP <- function(Y , k, M, controls, toCorrect, withExtra, withW = FALSE, withAlpha = FALSE) {
        if(any(is.na(Y[, controls])))
        {
                stop("The negative control variables should never be NA")
        }
	if(k >= nrow(Y))
	{
		stop("Input k cannot be larger than or equal to the number of rows in the Y matrix")
	}
	if(k > length(controls))
	{
		stop("Input k cannot be larger than the number of negative controls")
	}
    	.Call('_RUVIIIC_RUVIIIC', PACKAGE = 'RUVIIIC', Y, k, M, controls, toCorrect, withExtra, withW, withAlpha)
}
RUVIII_C_Varying_CPP <- function(Y, k, M, potentialControls, toCorrect, withExtra, withW = FALSE, withAlpha = FALSE) {
	if(k >= nrow(Y))
	{
		stop("Input k cannot be larger than or equal to the number of rows in the Y matrix")
	}
	if(k > length(potentialControls))
	{
		stop("Input k cannot be larger than the number of negative controls")
	}
    	.Call('_RUVIIIC_RUVIIIC_Varying', PACKAGE = 'RUVIIIC', Y, k, M, potentialControls, toCorrect, withExtra, withW, withAlpha)
}

