# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RUVIIIC_CPP <- function(Y, k, M, controls, toCorrect, withExtra, withW, withAlpha, progress) {
    .Call('_RUVIIIC_RUVIIIC_CPP', PACKAGE = 'RUVIIIC', Y, k, M, controls, toCorrect, withExtra, withW, withAlpha, progress)
}

RUVIIIC_Varying_CPP <- function(Y, k, M, potentialControls, toCorrect, withExtra, withW, withAlpha, progress) {
    .Call('_RUVIIIC_RUVIIIC_Varying_CPP', PACKAGE = 'RUVIIIC', Y, k, M, potentialControls, toCorrect, withExtra, withW, withAlpha, progress)
}

RUVIIIC_omp_set_num_threads <- function(num) {
    .Call('_RUVIIIC_RUVIIIC_omp_set_num_threads', PACKAGE = 'RUVIIIC', num)
}

RUVIIIC_omp_get_num_threads <- function() {
    .Call('_RUVIIIC_RUVIIIC_omp_get_num_threads', PACKAGE = 'RUVIIIC')
}

